# -*- coding: utf-8 -*-
"""books_preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12EjgzJ9zcuP4_tTUXMr_f8DrLqoAUXFM
"""

from google.colab import drive
import gzip
import pandas as pd
import pickle

drive.mount('/content/drive')

all_books = pd.read_json("/content/drive/MyDrive/goodreads_books_history_biography.json.gz", compression='gzip', lines=True)

all_books

books = {}
for idx, row in all_books.iterrows():
    books[row['book_id']] = {'title': row['title'], 'rating': row['average_rating'], 'reviews':[], 'similar':[]}

with open('/content/drive/MyDrive/books.pickle', 'wb') as f:
    pickle.dump(books, f, protocol=pickle.HIGHEST_PROTOCOL)

with open('/content/drive/MyDrive/all_books.pickle', 'wb') as f:
    pickle.dump(all_books, f, protocol=pickle.HIGHEST_PROTOCOL)

len(books)