# -*- coding: utf-8 -*-
"""reviews_preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5Nw5Ehr8wfgLKh7QWoJP53fa5VGZVO_
"""

from google.colab import drive
import gzip
import pandas as pd
import pickle

drive.mount('/content/drive')

all_reviews = pd.read_json("/content/drive/MyDrive/goodreads_reviews_history_biography.json.gz", compression='gzip', lines=True)

all_reviews

reviews = {}
for idx, row in all_reviews.iterrows():
    reviews[row['review_id']] = {'review_text': row['review_text'], 'rating': row['rating'], 'votes': row['n_votes'], 'user_id': row['user_id'], 'book_id': row['book_id']}

with open('/content/drive/MyDrive/reviews.pickle', 'wb') as f:
    pickle.dump(reviews, f, protocol=pickle.HIGHEST_PROTOCOL)

reviews['c23406fb584d6304d1dd4c75ce26ea3a']

